# Generated by Django 2.2.16 on 2020-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drifter_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicheng', models.CharField(default='lubenwei', max_length=50, verbose_name='nicheng')),
                ('username', models.CharField(max_length=12, verbose_name='username')),
                ('password', models.CharField(max_length=12, verbose_name='password')),
                ('sex', models.IntegerField(choices=[(0, 'male'), (1, 'female')], verbose_name='sex')),
                ('date', models.CharField(max_length=50, verbose_name='date_of_birth')),
                ('hobby', models.TextField(verbose_name='hobby')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
