# Generated by Django 2.2.16 on 2020-11-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drifter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drifter_user',
            name='date',
            field=models.CharField(max_length=50, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='drifter_user',
            name='email',
            field=models.CharField(max_length=50, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='drifter_user',
            name='hobby',
            field=models.TextField(null=True, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='drifter_user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')], null=True, verbose_name='性别'),
        ),
    ]
