# Generated by Django 2.2.16 on 2020-11-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drifter', '0002_auto_20201108_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='drifter_ocean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, null=True, verbose_name='owner')),
                ('content', models.TextField(max_length=100, null=True, verbose_name='content')),
                ('state', models.IntegerField(choices=[(0, 'unfound'), (1, 'found')], null=True, verbose_name='state')),
                ('finder', models.CharField(max_length=50, null=True, verbose_name='finder')),
                ('reply', models.TextField(max_length=100, null=True, verbose_name='reply')),
            ],
        ),
    ]
